<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Patch panels</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jointjs/2.2.1/joint.css" integrity="sha256-Mktq+NUuOY09dwojosTkhuIBFELOi6CBWMRtKuJjhf4=" crossorigin="anonymous" />
</head>

<body>
        <main role="main" class="container-fluid">
