<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Patch panels</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jointjs/2.2.1/joint.css" integrity="sha256-Mktq+NUuOY09dwojosTkhuIBFELOi6CBWMRtKuJjhf4=" crossorigin="anonymous" />

    <link rel="stylesheet" href="/assets/css/site.css">
</head>

<body>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">DocGen</a>
      <!-- <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          <a class="nav-link" href="#">Sign out</a>
        </li>
      </ul> -->
    </nav>
    <div class="container-fluid">
        <div class="row">
            <?php echo $this->fetch("_elements/sidebar.phtml", []); ?>

            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
