<?php echo $this->fetch("_elements/header.phtml", []); ?>



<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom title">
    <h1 class="h2">Fiber Map</h1>
    <div class="form-group mb-2 mb-md-0">
        <div class="">
            <select class="form-control form-control-sm" id="selectRack">
                <option value="">Select rack</option>
            </select>
        </div>
    </div>
</div>

<div id="diagram" class="row">Loading</div>

<?php echo $this->fetch("_elements/footer.phtml", [
    "scripts" => [
        'diagram_top'
    ]
]); ?>
